/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as MarcaSlugRouteImport } from './routes/marca.$slug'
import { Route as ObjetivoSlugRouteImport } from './routes/objetivo.$slug'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaSlugRoute = MarcaSlugRouteImport.update({
  id: '/marca/$slug',
  path: '/marca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivoSlugRoute = ObjetivoSlugRouteImport.update({
  id: '/objetivo/$slug',
  path: '/objetivo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/categoria/$slug'
    | '/marca/$slug'
    | '/objetivo/$slug'
    | '/produtos/$slug'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/categoria/$slug'
    | '/marca/$slug'
    | '/objetivo/$slug'
    | '/produtos/$slug'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/categoria/$slug'
    | '/marca/$slug'
    | '/objetivo/$slug'
    | '/produtos/$slug'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  MarcaSlugRoute: typeof MarcaSlugRoute
  ObjetivoSlugRoute: typeof ObjetivoSlugRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca/$slug': {
      id: '/marca/$slug'
      path: '/marca/$slug'
      fullPath: '/marca/$slug'
      preLoaderRoute: typeof MarcaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivo/$slug': {
      id: '/objetivo/$slug'
      path: '/objetivo/$slug'
      fullPath: '/objetivo/$slug'
      preLoaderRoute: typeof ObjetivoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  MarcaSlugRoute: MarcaSlugRoute,
  ObjetivoSlugRoute: ObjetivoSlugRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
